// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnqVeOgcw4ZbyevzkZjQnT7HWZHwMQcYE',
    appId: '1:774405267031:web:c95e693eec0e67fc44cd12',
    messagingSenderId: '774405267031',
    projectId: 'to-do-list-app-007',
    authDomain: 'to-do-list-app-007.firebaseapp.com',
    storageBucket: 'to-do-list-app-007.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMyiPS2ShsC8W9fRtZyaSEOjpphdCjZDo',
    appId: '1:774405267031:android:850c82cfe18cda9144cd12',
    messagingSenderId: '774405267031',
    projectId: 'to-do-list-app-007',
    storageBucket: 'to-do-list-app-007.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvaw5N6WlVRjN92t8fOhDwviEJ6pieAe0',
    appId: '1:774405267031:ios:00662667cf25a2ba44cd12',
    messagingSenderId: '774405267031',
    projectId: 'to-do-list-app-007',
    storageBucket: 'to-do-list-app-007.firebasestorage.app',
    iosBundleId: 'com.example.toDoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvaw5N6WlVRjN92t8fOhDwviEJ6pieAe0',
    appId: '1:774405267031:ios:00662667cf25a2ba44cd12',
    messagingSenderId: '774405267031',
    projectId: 'to-do-list-app-007',
    storageBucket: 'to-do-list-app-007.firebasestorage.app',
    iosBundleId: 'com.example.toDoListApp',
  );
}
